/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Crc20 } from "./Crc20";
export * as factories from "./factories";
export { Crc20__factory } from "./factories/Crc20__factory";
